account:
  encrypt: false
  password: 1
  relogin:
    delay: 3
    interval: 3
    max-times: 0
  status: 0
  uin: 1
  use-sso-address: true
database:
  leveldb:
    enable: true
default-middlewares:
  access-token: 
  filter: 
  rate-limit:
    bucket: 1
    enabled: false
    frequency: 1
heartbeat:
  interval: 5
message:
  extra-reply-data: false
  fix-url: false
  force-fragment: false
  ignore-invalid-cqcode: false
  post-format: string
  proxy-rewrite: 
  remove-reply-at: false
  report-self-message: false
  skip-mime-scan: false
output:
  debug: false
  log-aging: 15
  log-force-new: true
  log-level: warn
servers:
- ws-reverse: []
- ws-reverse:
    api: ws://your_websocket_api.server
    event: ws://your_websocket_event.server
    middlewares:
      access-token: 
      filter: 
      rate-limit:
        bucket: 1
        enabled: false
        frequency: 1
    reconnect-interval: 3000
    universal: ws://127.0.0.1:9000/cqhttp/ws
